### ISSUE TITLE
Split code and tests into one file per function

### ISSUE THREAD

**Issue by florianm** [carlopacioni/vortexR#25]
This will increase readability and make vortexR more maintainable.

**Comment by carlopacioni** [comment]
I think one file per function is a bit of an overkill. I have separated the code by functional groups. If you are happy with this, you can close the issue.

**Comment by florianm** [comment]
To be honest, I'm still in favour of one file per function, based on:

* Personal preference: scrolling to a function in a list of files is easier than scrolling / searching within one large file. 
* Following the example set in other packages: e.g. https://github.com/ropensci/ckanr/tree/master/R
* Splitting into functional groups requires scrolling and searching through several files.

**Comment by carlopacioni** [comment]
ha,ha, we won't ever agree on this! ;-) 
The only real advantage I see with 1-FUN-1-file is that you can put the function side by side (but you could do that anyway if you open the same file with RStudio and the other with something like notepad++). As for the rest, I am tempted to argue that splitting in 1-FUN-1-file means that:
- you can't do a global search/replace id you decide, e.g. to change the name of a function or an argument, but you have to iterate across files
- It doesn't follow Hadley's recommendation, which seems to be generally accepted (From http://r-pkgs.had.co.nz/r.html#r-organising : While you’re free to arrange functions into files as you wish, the two extremes are bad: don’t put all functions into one file and don’t put each function into its own separate file. (It’s OK if some files only contain one function, particularly if the function is large or has a lot of documentation.). ).
- In reality, you don't have to scroll either ways because RStudio provides plenty of ways to jump from one FUN to another: e.g. CTRL+.  or CTRL+SHIFT+J

but I can see all this is quite subjective and I'll give in and let you go ahead and do the changes you see appropriate.

**Comment by florianm** [comment]
Hadley and the RStudio shortcuts are good arguments pro grouping. As I couldn't find any guidance on number of functions per file in the CRAN policy, I'm happy to keep things as is and will close this issue as resolved.

**Comment by carlopacioni** [comment]
Keep in mind that we can re-assess one function at the time  when we deal with the other issues (e.g. #5, #10) as these will require some re-factoring of the function. One thing I was thinking is that we may want to split some of the longer analytical functions (e.g. pairwise and fit_regression?) and leave together all the easy/short ones? Again, we can do this when we work on them next.
